
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.2.0"


[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"	# For K8s 1.10.x

[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.4"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.10.4"

[[override]]
  name = "github.com/superwhiskers/yaml"
  branch = "v2"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.4"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.10.4"

[[override]]
  name = "github.com/russross/blackfriday"
  branch = "master"


[prune]
  go-tests = true
  unused-packages = true
